<a href="https://colab.research.google.com/github/AatishKumar649/MultipleLinearRegression/blob/main/MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:

X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)
# make_regresion is function in scikit learn using which we can make datasets of multiple dimension in linear regression


In [3]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})
# This is code how to convert data in dataframe so that we can work easily on the data


In [4]:

df.shape

(100, 3)

In [5]:
df.head()

feature1  feature2      target
0 -1.397826  0.443278  -39.520307
1  0.271933  0.619967  105.914263
2  1.142013 -0.095968  103.278078
3 -0.698513  0.987827   45.863818
4  1.230586  1.576366  200.672603

In [6]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
# plotlt is a library used to plot graph or 3d visuals
fig.show()

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [8]:

from sklearn.linear_model import LinearRegression

In [9]:
lr = LinearRegression()
# Made an object of Linear Regression function


In [10]:
lr.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred = lr.predict(X_test)

In [13]:

print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 58.586570987892
MSE 5207.127621798603
R2 score -0.2152997103171812


In [15]:

x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = lr.predict(final).reshape(10,10)

z = z_final

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [16]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [17]:

lr.coef_

array([19.4967922 , 64.29495239])

In [18]:

lr.intercept_


-2.1764264590832676

# **Code From scratch for multiple Linear Regression **

In [19]:
import numpy as np
from sklearn.datasets import load_diabetes
# Sklearn Library already has a dataset of Diabetes in which 442 patient data is recorded and we can call that dataset using function called load_diabetes and it internally coverts the data set into numpy array

In [20]:
X,y = load_diabetes(return_X_y=True)

In [21]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [22]:
X.shape

(442, 10)

In [23]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [24]:
y.shape

(442,)

# **Using Sklearn's Linear Regression**

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [27]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
reg = LinearRegression()

In [30]:
reg.fit(X_train,y_train)

LinearRegression()

In [31]:
y_pred = reg.predict(X_test)

In [32]:
from sklearn.metrics import r2_score

In [33]:
r2_score(y_test,y_pred)

0.4399338661568968

In [34]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [35]:
reg.intercept_

151.88331005254167

# **Making our own Linear Regression Class**

In [36]:
class MeraLR:
  # Made a class named MeraLR

    def __init__(self):
      # creating a constructor function and self initialized two values
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [37]:
lr = MeraLR()
# Created object of meraLR class

In [38]:
lr.fit(X_train,y_train)

In [39]:
X_train.shape

(353, 10)

In [40]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [41]:
y_pred = lr.predict(X_test)

In [42]:
r2_score(y_test,y_pred)

0.43993386615689634

In [43]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [44]:
lr.intercept_

151.88331005254165